const Map<String, List<Map<String, dynamic>>> insumos = {
  'BALDES': [
    {
      "nome": "BAUNILHA, PAÇOCA E DOCE DE LEITE",
      "minimo": "2/4",
      "tipo": "Balde"
    },
    {"nome": "BEM CASADO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "FLOCOS DA AMAZÔNIA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "COCADA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "DOCE DE LEITE ORAMA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CAFÉ DA MANTIQUEIRA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "PAÇOCA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BANANA CARAMELADA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MENTA COM CHOCOLATE", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BOLO DE CENOURA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CACAU BAHIA COM LARANJA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BRIGADEIRO MEIO AMARGO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "REQUEIJÃO COM GOIABADA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MILHO VERDE", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MOUSSE DE MARACUJÁ COM BOLO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "COCO COM ABÓBORA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MARACUJÁ E MEL", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MANGA COM ALECRIM", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MORANGO COM HORTELÃ", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "LIMÃO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CUPUAÇU", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "AMORA DO CAXAMBU", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "UVA VITÓRIA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "UVA NIÁGARA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "TAMARINDO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "MURICI", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CAMBUCI", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "SIRIGUELA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CAJÁ", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "AÇAÍ DA AMAZÔNIA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BRIGADEIRO COM WHEY ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BANANA COM WHEY ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CARAMELO COM WHEY ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "AÇAÍ VEGANO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "PITAYA COM MORANGO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CHOCOLATE VEGANO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "UVA VEGANO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "LIMÃO COM CAPIM SANTO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "COCO VERDE VEGANO ZERO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "AÇAÍ C/ MORANGO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "AÇAÍ C/ BANANA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "GROSELHA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "FRUTAS AO VINHO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "ABACAXI AO VINHO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "VINHO QUENTE", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "PARMESÃO COM GELEIA DE UVA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "PANNACOTA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "ESPUMANTE COM PÊSSEGO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BAUNILHA COM FIGO E MEL", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "CACAU COM LEITE DE CABRA", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "BAUNILHA C/ PAÇOCA (CABRA)", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "UVA ISIS VEGANO", "minimo": "2/4", "tipo": "Balde"},
    {"nome": "UVAIA", "minimo": "2/4", "tipo": "Balde"},
  ],
  'POTES': [
    {"nome": "BAUNILHA, PAÇOCA E DOCE DE LEITE", "minimo": "2", "tipo": "Pote"},
    {"nome": "BEM CASADO", "minimo": "2", "tipo": "Pote"},
    {"nome": "FLOCOS DA AMAZÔNIA", "minimo": "2", "tipo": "Pote"},
    {"nome": "COCADA", "minimo": "2", "tipo": "Pote"},
    {"nome": "DOCE DE LEITE ORAMA", "minimo": "2", "tipo": "Pote"},
    {"nome": "CAFÉ DA MANTIQUEIRA", "minimo": "2", "tipo": "Pote"},
    {"nome": "PAÇOCA", "minimo": "2", "tipo": "Pote"},
    {"nome": "BANANA CARAMELADA", "minimo": "2", "tipo": "Pote"},
    {"nome": "MENTA COM CHOCOLATE", "minimo": "2", "tipo": "Pote"},
    {"nome": "BOLO DE CENOURA", "minimo": "2", "tipo": "Pote"},
    {"nome": "CACAU BAHIA COM LARANJA", "minimo": "2", "tipo": "Pote"},
    {"nome": "BRIGADEIRO MEIO AMARGO", "minimo": "2", "tipo": "Pote"},
    {"nome": "REQUEIJÃO COM GOIABADA", "minimo": "2", "tipo": "Pote"},
    {"nome": "MILHO VERDE", "minimo": "2", "tipo": "Pote"},
    {"nome": "MOUSSE DE MARACUJÁ COM BOLO", "minimo": "2", "tipo": "Pote"},
    {"nome": "COCO COM ABÓBORA", "minimo": "2", "tipo": "Pote"},
    {"nome": "MARACUJÁ E MEL", "minimo": "2", "tipo": "Pote"},
    {"nome": "MANGA COM ALECRIM", "minimo": "2", "tipo": "Pote"},
    {"nome": "MORANGO COM HORTELÃ", "minimo": "2", "tipo": "Pote"},
    {"nome": "LIMÃO", "minimo": "2", "tipo": "Pote"},
    {"nome": "CUPUAÇU", "minimo": "2", "tipo": "Pote"},
    {"nome": "AMORA DO CAXAMBU", "minimo": "2", "tipo": "Pote"},
    {"nome": "UVA VITÓRIA", "minimo": "2", "tipo": "Pote"},
    {"nome": "UVA NIÁGARA", "minimo": "2", "tipo": "Pote"},
    {"nome": "TAMARINDO", "minimo": "2", "tipo": "Pote"},
    {"nome": "MURICI", "minimo": "2", "tipo": "Pote"},
    {"nome": "CAMBUCI", "minimo": "2", "tipo": "Pote"},
    {"nome": "SIRIGUELA", "minimo": "2", "tipo": "Pote"},
    {"nome": "CAJÁ", "minimo": "2", "tipo": "Pote"},
    {"nome": "AÇAÍ DA AMAZÔNIA", "minimo": "2", "tipo": "Pote"},
    {"nome": "BRIGADEIRO COM WHEY ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "BANANA COM WHEY ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "CARAMELO COM WHEY ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "AÇAÍ VEGANO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "PITAYA COM MORANGO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "CHOCOLATE VEGANO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "UVA VEGANO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "LIMÃO COM CAPIM SANTO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "AÇAÍ C/ MORANGO", "minimo": "2", "tipo": "Pote"},
    {"nome": "AÇAÍ C/ BANANA", "minimo": "2", "tipo": "Pote"},
    {"nome": "GROSELHA", "minimo": "2", "tipo": "Pote"},
    {"nome": "COCO VERDE VEGANO ZERO", "minimo": "2", "tipo": "Pote"},
    {"nome": "FRUTAS AO VINHO", "minimo": "2", "tipo": "Pote"},
    {"nome": "ABACAXI AO VINHO", "minimo": "2", "tipo": "Pote"},
    {"nome": "VINHO QUENTE", "minimo": "2", "tipo": "Pote"},
    {"nome": "PARMESÃO COM GELEIA DE UVA", "minimo": "2", "tipo": "Pote"},
    {"nome": "PANNACOTA", "minimo": "2", "tipo": "Pote"},
    {"nome": "ESPUMANTE COM PÊSSEGO", "minimo": "2", "tipo": "Pote"},
    {"nome": "BAUNILHA COM FIGO E MEL", "minimo": "2", "tipo": "Pote"},
    {"nome": "CACAU COM LEITE DE CABRA", "minimo": "2", "tipo": "Pote"},
    {"nome": "BAUNILHA C/ PAÇOCA (CABRA)", "minimo": "2", "tipo": "Pote"},
    {"nome": "UVA ISIS VEGANO", "minimo": "2", "tipo": "Pote"},
    {"nome": "UVAIA", "minimo": "2", "tipo": "Pote"},
  ],
  'COOKIES': [
    {
      'nome': 'TRAD. BAUNILHA AO LEITE - BAUNILHA + CHOC. AO LEITE',
      'minimo': '20',
      'tipo': 'Un'
    },
    {
      'nome': 'BAUNILHA BRANCO - BAUNILHA + CHOCOLATE BRANCO',
      'minimo': '20',
      'tipo': 'Un'
    },
    {'nome': 'BANANA - CHOC LEITE + BANANA', 'minimo': '20', 'tipo': 'Un'},
    {
      'nome': 'BAUNILHA COM CAFÉ - BAUNILHA + CAFÉ + CHOC. AO LEITE ',
      'minimo': '20',
      'tipo': 'Un'
    },
    {
      'nome': 'DUPLO CHOCOLATE - CHOCOLATE 70% + CHOCOLATE 50%',
      'minimo': '20',
      'tipo': 'Un'
    },
    {
      'nome': 'BROWNIE - CHOCOLATE 50% + CASTANHAS DE CAJU',
      'minimo': '20',
      'tipo': 'Un'
    },
    {
      'nome': 'CHOCOLATE AO LEITE - CHOCOLATE + CHOC. AO LEITE',
      'minimo': '20',
      'tipo': 'Un'
    },
  ],
  'PÃO DE QUEIJO': [
    {'nome': 'PAO DE QUEIJO GRANDE 90 GRAMAS', 'minimo': '10', 'tipo': 'Un'},
    {'nome': 'PAO DE QUEIJO MINI 20 GRAMAS', 'minimo': '50', 'tipo': 'Un'},
  ],
  'SECOS': [
    {'nome': 'BOLACHINHA BAUNILHA', 'minimo': '10', 'tipo': 'Un'},
    {'nome': 'BOLACHINHA CANELA', 'minimo': '10', 'tipo': 'Un'},
    {'nome': 'BOLACHINHA CHOCOLATE', 'minimo': '10', 'tipo': 'Un'},
    {'nome': 'CONE VIAGEM BAUNILHA', 'minimo': '5', 'tipo': 'Un'},
    {'nome': 'CONE VIAGEM CANELA', 'minimo': '5', 'tipo': 'Un'},
    {'nome': 'CONE VIAGEM CHOCOLATE', 'minimo': '5', 'tipo': 'Un'},
    {"nome": "CAFÉ GRÃO", "minimo": "1", 'tipo': 'Sacos'},
    {"nome": "LARANJAS CRISTALIZADAS", "minimo": "200", 'tipo': 'g'},
    {"nome": "AVEIA", "minimo": "1", 'tipo': 'Kg'},
    {"nome": "FAROFA DE AMENDOIM", "minimo": "1", 'tipo': 'Kg'},
    {"nome": "CASTANHA GLACEADAS", "minimo": "1", 'tipo': 'Kg'},
    {"nome": "LASCAS DE COCO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "GRANOLA", "minimo": "1", 'tipo': 'Kg'},
  ],
  "TOPPINGS": [
    {"nome": "MASSA BOLO DE COCO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "DOCE DE BANANA P/TOPPING", "minimo": "1", 'tipo': 'Un'},
    {"nome": "DOCE DE GOIABA P/TOPPING", "minimo": "1", 'tipo': 'Un'},
    {"nome": "CALDA DE BRIGADEIRO P/ TOPPING", "minimo": "1", 'tipo': 'Un'},
    {"nome": "GANACHE DE LEITE", "minimo": "5", 'tipo': 'Un'},
    {"nome": "GANACHE MEIO AMARGA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "MASSA BAUNILHA CASQUINHA", "minimo": "5", 'tipo': 'Tubo'},
    {"nome": "MASSA BOLO CENOURA", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MASSA BOLO CHOCOLATE", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MASSA CANELA CASQUINHAS", "minimo": "5", 'tipo': 'Tubo'},
    {"nome": "CALDA DE DOCE DE LEITE P/TOPPING", "minimo": "1", 'tipo': 'Un'},
    {
      "nome": "CALDA DE FRUTAS DE MORANGO P/TOPPING",
      "minimo": "1",
      'tipo': 'Un'
    },
  ],
  'PERECÍVEIS': [
    {"nome": "MORANGO", "minimo": "50", 'tipo': 'g'},
    {"nome": "BANANA PRATA", "minimo": "3", 'tipo': 'Un'},
  ],
  "POLPAS": [
    {"nome": "ABACAXI", "minimo": "5", 'tipo': 'Un'},
    {"nome": "AMORA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "CACAU", "minimo": "5", 'tipo': 'Un'},
    {"nome": "CAJÁ", "minimo": "5", 'tipo': 'Un'},
    {"nome": "CAMBUCI", "minimo": "5", 'tipo': 'Un'},
    {"nome": "CUPUAÇU", "minimo": "5", 'tipo': 'Un'},
    {"nome": "FRUTAS VERMELHAS", "minimo": "5", 'tipo': 'Un'},
    {"nome": "GRAVIOLA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "JENIPAPO", "minimo": "5", 'tipo': 'Un'},
    {"nome": "LIMÃO", "minimo": "5", 'tipo': 'Un'},
    {"nome": "MANGA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "MARACUJÁ", "minimo": "5", 'tipo': 'Un'},
    {"nome": "MORANGO POLPA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "MURICI", "minimo": "5", 'tipo': 'Un'},
    {"nome": "PITAYA VERMELHA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "SIRIGUELA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "TAMARINDO", "minimo": "5", 'tipo': 'Un'},
    {"nome": "UMBÚ", "minimo": "5", 'tipo': 'Un'},
    {"nome": "UVA POLPA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "UVAIA", "minimo": "5", 'tipo': 'Un'}
  ],
  "INSUMOS": [
    {"nome": "MARGARINA", "minimo": "1", 'tipo': 'Kg'},
    {"nome": "LEITE DE CAIXA", "minimo": "1", 'tipo': 'Un'},
  ],
  "DECORAÇÃO": [
    {"nome": "DOCE DE LEITE PASTOSO", "minimo": "2/4", 'tipo': '-'},
    {"nome": "CHOCOLATE P/ FLOCOS", "minimo": "", 'tipo': '-'},
    {"nome": "CHOCOLATE BRANCO", "minimo": "", 'tipo': '-'},
    {"nome": "CREME DE CAJU C/ CHOCOLATE", "minimo": "", 'tipo': '-'},
  ],
  'ÁGUA': [
    {"nome": "ÁGUA COM GÁS", "minimo": "1", 'tipo': 'Fardo'},
    {"nome": "ÁGUA SEM GÁS", "minimo": "1", 'tipo': 'Fardo'},
  ],
  'DESCARTÁVEIS': [
    {"nome": "KRAFT PÃO DE QUEIJO/COOKIES VIAGEM", "minimo": "5", 'tipo': 'Un'},
    {"nome": "AÇÚCAR SACHE", "minimo": "2/4", 'tipo': 'Caixa'},
    {"nome": "ADOÇANTE SACHE", "minimo": "2/4", 'tipo': 'Caixa'},
    {"nome": "ISOPOR (PROMOÇÃO)", "minimo": "10", 'tipo': 'Un'},
    {"nome": "CANUDO SACODE/SUCO", "minimo": "20", 'tipo': 'Un'},
    {"nome": "COLHER DE PLÁSTICO VIAGEM", "minimo": "2/4", 'tipo': 'Un'},
    {"nome": "COPO PLÁSTICO 450ML", "minimo": "20", 'tipo': 'Un'},
    {"nome": "GUARDANAPO", "minimo": "2/4", 'tipo': 'Caixa'},
    {"nome": "INTERFOLHA DE PAREDE", "minimo": "1", 'tipo': 'Sacos'},
    {"nome": "LUVAS", "minimo": "1", 'tipo': 'Caixa'},
    {"nome": "PA DE MADEIRA AMOSTRA", "minimo": "2/4", 'tipo': 'Caixa'},
    {
      "nome": "PA DE MADEIRA GRANDE P/ SERVIR",
      "minimo": "2/4",
      'tipo': 'Caixa'
    },
    {"nome": "PALITO MEXEDOR DE CAFÉ", "minimo": "1/4", 'tipo': 'Caixa'},
    {"nome": "POTE SORVETE ORAMA 80ML", "minimo": "10", 'tipo': 'Sacos'},
    {"nome": "POTE SORVETE ORAMA 120ML", "minimo": "10", 'tipo': 'Sacos'},
    {"nome": "POTE SORVETE ORAMA 240ML", "minimo": "10", 'tipo': 'Sacos'},
    {"nome": "POTE SORVETE ORAMA 350ML", "minimo": "10", 'tipo': 'Sacos'},
    {"nome": "POTE SORVETE VIAGEM 500ML", "minimo": "5", 'tipo': 'Sacos'},
    {"nome": "ROLO FILME", "minimo": "1", 'tipo': 'Un'},
    {"nome": "SACOLA PARDA PAPEL ORAMA", "minimo": "20", 'tipo': 'Un'},
    {"nome": "TAMPA SACODE", "minimo": "15", 'tipo': 'Un'},
    {"nome": "TOUCAS DESCARTÁVEIS", "minimo": "10", 'tipo': 'Un'},
    {"nome": "BOBINA MÁQUINA", "minimo": "2", 'tipo': 'Un'},
    {"nome": "BOBINA CUPOM FISCAL", "minimo": "2", 'tipo': 'Un'},
    {"nome": "PAPEL HIGIENICO", "minimo": "5", 'tipo': 'Un'}
  ],
  'LIMPEZA': [
    {"nome": "ALCOOL 70%", "minimo": "1", 'tipo': 'Litro'},
    {"nome": "ALCOOL GEL CLIENTE", "minimo": "2", 'tipo': 'Litro'},
    {"nome": "CLORO", "minimo": "2", 'tipo': 'Litro'},
    {"nome": "DETERGENTE", "minimo": "1", 'tipo': 'Litro'},
    {"nome": "ESPONJA", "minimo": "4", 'tipo': 'Un'},
    {"nome": "MOPP", "minimo": "1", 'tipo': 'Un'},
    {"nome": "PANOS BRANCOS", "minimo": "5", 'tipo': 'Un'},
    {"nome": "PERFEX", "minimo": "2", 'tipo': 'Rolo'},
    {"nome": "RODO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "SABONETE INCOLOR P/ MÃOS", "minimo": "1", 'tipo': 'Un'},
    {"nome": "SACO DE LIXO 100L PRETO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "SACO DE LIXO 30L PRETO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "VASSOURA", "minimo": "2", 'tipo': 'Un'},
    {"nome": "VEJA LIMPA VIDRO TRANSPARENTE", "minimo": "2", 'tipo': 'Un'},
    {"nome": "VEJA MULTIUSO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "DESINFETANTE", "minimo": "1", 'tipo': 'Litro'},
  ],
  'UNIFORMES': [
    {"nome": "AVENTAL JEANS", "minimo": "3", 'tipo': 'Un'},
    {"nome": "CAMISETA", "minimo": "3", 'tipo': 'Un'},
    {"nome": "ETIQUETA VALIDADE", "minimo": "2", 'tipo': 'Un'},
    {"nome": "TOUCA DE TECIDO", "minimo": "3", 'tipo': 'Un'}
  ],
  'UTENSÍLIOS': [
    {"nome": "BALDE DE ÁGUA", "minimo": "3", 'tipo': 'Un'},
    {"nome": "BOLEADOR AÇO", "minimo": "4", 'tipo': 'Un'},
    {"nome": "CAIXA SOM JBL", "minimo": "1", 'tipo': 'Un'},
    {"nome": "COLHER DE METAL", "minimo": "", 'tipo': 'Un'},
    {"nome": "CUBAS DE AÇO SORVETE", "minimo": "1", 'tipo': 'Un'},
    {"nome": "CUMBUCA DE PORCELANA", "minimo": "12", 'tipo': 'Un'},
    {"nome": "ESPATULA AÇO", "minimo": "3", 'tipo': 'Un'},
    {"nome": "ESPÁTULA BORRACHA (MANTEIGA)", "minimo": "1", 'tipo': 'Un'},
    {"nome": "ESTUFA DE CASQUINHAS", "minimo": "1", 'tipo': 'Un'},
    {"nome": "FACA DE SERRA PÃO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "GRILL DE PÃO", "minimo": "1", 'tipo': 'Un'},
    {"nome": "LIQUIDIFICADOR", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MÁQUINA DE CASQUINHA", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MIXER MILK SHAKE", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MOLDE DE CASQUINHA", "minimo": "2", 'tipo': 'Un'},
    {"nome": "PEGADOR CASQUINHA", "minimo": "1", 'tipo': 'Un'},
    {"nome": "PIRES GRANDE", "minimo": "5", 'tipo': 'Un'},
    {"nome": "PIRES PEQUENO", "minimo": "5", 'tipo': 'Un'},
    {"nome": "POTE AÇAÍ GRANDE", "minimo": "1", 'tipo': 'Un'},
    {"nome": "XÍCARA CAFÉ GRANDE", "minimo": "5", 'tipo': 'Un'},
    {"nome": "XÍCARA CAFÉ PEQUENA", "minimo": "5", 'tipo': 'Un'},
    {"nome": "CRONÔMETRO", "minimo": "3", 'tipo': 'Un'},
    {"nome": "MÁQUINA DE CAFÉ", "minimo": "1", 'tipo': 'Un'},
    {"nome": "MOEDOR DE CAFÉ", "minimo": "1", 'tipo': 'Un'},
  ],
  'PAPELARIA': [
    {"nome": "CANETA BIC", "minimo": "3", 'tipo': 'Un'},
    {"nome": "CANETA PERMANENTE", "minimo": "2", 'tipo': 'Un'},
    {"nome": "FITA DUREX", "minimo": "1", 'tipo': 'Un'},
    {"nome": "GRAMPO", "minimo": "2/4", 'tipo': '-'},
    {"nome": "POST-IT", "minimo": "3", 'tipo': 'Un'},
    {"nome": "GRAMPEADOR", "minimo": "1", 'tipo': 'Un'},
  ],
};
