// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi26I2WC-3Zs0NbJcRsdkjvQFeObqTLj4',
    appId: '1:681609262580:web:a7abe98d80f89187e075a1',
    messagingSenderId: '681609262580',
    projectId: 'oramaloja',
    authDomain: 'oramaloja.firebaseapp.com',
    storageBucket: 'oramaloja.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2kcPMyudjkGohevS98HXR4RdB1uIdNfY',
    appId: '1:681609262580:android:502d5ba58414b4cde075a1',
    messagingSenderId: '681609262580',
    projectId: 'oramaloja',
    storageBucket: 'oramaloja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrL4gBqMkRutjueAtO_juVGazjeB9ZNPo',
    appId: '1:681609262580:ios:3517c84f93af673fe075a1',
    messagingSenderId: '681609262580',
    projectId: 'oramaloja',
    storageBucket: 'oramaloja.firebasestorage.app',
    iosBundleId: 'com.example.oramaLojas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi26I2WC-3Zs0NbJcRsdkjvQFeObqTLj4',
    appId: '1:681609262580:web:08eb34e1399aceb1e075a1',
    messagingSenderId: '681609262580',
    projectId: 'oramaloja',
    authDomain: 'oramaloja.firebaseapp.com',
    storageBucket: 'oramaloja.firebasestorage.app',
  );
}
